### ISSUE TITLE
type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.

### ISSUE THREAD

**Issue by misogihagi** [wheatjs/vite-plugin-vue-type-imports#30]
Related #25 

Hello, thank you for your help before.

By the way, I found another problem.
 
I used 
`
export type props=Partial<{ msg: string }>
`
instead of 
`
export type props={ msg: string } 
`
and the example problem occurred again.

> [vite:vue] [@vue/compiler-sfc] type argument passed to defineProps() must be a literal type, or a reference to an interface or literal type.
> 
> /vitest-test/src/components/HelloWorld.vue
> 5  |  
> 6  |  
> 7  |  defineProps<props>()
>    |              ^^^^^
> 8  |  
> 9  |  
> 
> 

Here is my [repp](https://github.com/misogihagi/vitest-test/tree/vue).

**Comment by Zolyn** [comment]
![image](https://user-images.githubusercontent.com/35414841/189931309-da33fd64-e2d2-4a6a-91b0-2520a6e52834.png)

>[These types](https://www.typescriptlang.org/docs/handbook/2/types-from-types.html) are not supported.

See [Known limitations](https://github.com/wheatjs/vite-plugin-vue-type-imports/blob/main/README.md#known-limitations)

The plugin just simply extracts types from files, it does not do static analysis.

It's hard to do static analysis which behaves as same as TS due to my poor knowledge of TS's type system.

We will mark this issue as an enhancement. And we hope that we can find an efficient way to achieve this.

**Comment by Zolyn** [comment]
I added the `duplicate` label because there was already an identical problem. (#28 )

**Comment by Zolyn** [comment]
We temporarily close this issue as duplicate, you can keep an eye on #28
